version: '3.7'
services:
  nginx:
    image: nginx:alpine
    ports:
      - 127.0.0.1:80:80
    volumes:
      - .:/usr/share/nginx/html:ro
  mocha:
    image: blueimp/mocha-chrome
    command: http://nginx/test
    environment:
      - WAIT_FOR_HOSTS=nginx:80
    depends_on:
      - nginx
